using System.Collections;
using UnityEngine;
using FMODUnity;

public class FMODManager : MonoBehaviour
{
    // Instancia ·nica (singleton)
    public static FMODManager instance;

    // El sistema de audio FMOD
    private FMOD.Studio.System fmodSystem;

    [SerializeField]
    FMODUnity.EventReference enemyDamaged;   // Seleccionado desde el inspector

    private FMOD.Studio.EventInstance enemydamagedEventInstance;

    // Asegurarse de que solo hay una instancia
    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(gameObject);  // Mantener AudioManager entre escenas
        }
        else
        {
            Destroy(gameObject);  // Evitar duplicados
        }

        // Inicializar FMOD Studio
        FMOD.Studio.System.create(out fmodSystem);

        //enemydamagedEventInstance.setVolume(0.1f);
        enemydamagedEventInstance = CreateEventInstance(enemyDamaged);
    }

    private void Start()
    {
        
    }

    private void OnDestroy()
    {
        StopEvent(enemydamagedEventInstance);
        RuntimeManager.UnloadBank("Master");
    }

    public void PlayEnemyDamaged()
    {
        enemydamagedEventInstance.start();
    }

    public FMOD.Studio.EventInstance CreateEventInstance(EventReference eventRef)
    {
        FMOD.Studio.EventInstance instance = RuntimeManager.CreateInstance(eventRef);
        return instance;
    }

    // Mķtodo para reproducir un evento FMOD
    public void PlayEvent(string eventPath)
    {
        FMOD.Studio.EventInstance eventInstance = FMODUnity.RuntimeManager.CreateInstance(eventPath);
        eventInstance.start();
        eventInstance.release(); // Release al terminar
    }

    // Mķtodo para reproducir un evento FMOD 2D (sin ubicaci¾n en el espacio)
    public void Play2DEvent(string eventPath)
    {
        FMODUnity.RuntimeManager.PlayOneShot(eventPath);
    }

    // Mķtodo para parar un evento
    public void StopEvent(FMOD.Studio.EventInstance eventInstance)
    {
        eventInstance.stop(FMOD.Studio.STOP_MODE.IMMEDIATE);
        eventInstance.release();
    }

    // Mķtodo para pausar un evento
    public void PauseEvent(FMOD.Studio.EventInstance eventInstance)
    {
        eventInstance.setPaused(true);
    }

    // Mķtodo para reanudar un evento
    public void ResumeEvent(FMOD.Studio.EventInstance eventInstance)
    {
        eventInstance.setPaused(false);
    }

    // Ejemplo de un mķtodo que se podrĒa llamar desde otros scripts
    public void PlaySoundEffect(string eventName)
    {
        string eventPath = "event:/" + eventName;  // Convierte el nombre del evento en el path correcto
        PlayEvent(eventPath);
    }
}